### ISSUE TITLE
Exception on no input or one white space

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#1]
I tried to inject an empty string or one space/tab, which threw System.IndexOutOfRangeException. The exception raises at [Source/CSharpInjector/TextPointer.cs#L85](https://github.com/lord-devious/csharpinjector/blob/5e5ebbf16c6e27320735f04b90a716a2be24b0a8/Source/CSharpInjector/TextPointer.cs#L85) if it is a white space and at [Source/CSharpInjector/TextPointer.cs#L112](https://github.com/lord-devious/csharpinjector/blob/5e5ebbf16c6e27320735f04b90a716a2be24b0a8/Source/CSharpInjector/TextPointer.cs#L112) if it is an empty string.

I guess this should throw an InjectorException with the information that the Main method is missing or just do nothing at all.

**Comment by lord-devious** [comment]
Hah! Excellent catch. Thanks.

**Comment by lord-devious** [comment]
Fixed
