### ISSUE TITLE
{ and } are duplicated

### ISSUE THREAD

**Issue by Wicorel** [lord-devious/csharpinjector#10]
Doubling of { and }

Simple Example

[code]
void main()
{
	bool b=true;
	if(b) {
		Echo("Test1");
	}
	else {
		Echo("Test2");
	}
}

[/code]
Results in:
[code]
#line 1 "script.cs"
void main()
{
	
InstructionCounter.CountMethodCalls();
#line 3 "script.cs"
bool b=true;
	if(b) {
		{
InstructionCounter.CountInstructions();
#line 5 "script.cs"
  Echo("Test1");
	}
	}else {
InstructionCounter.CountInstructions();
#line 7 "script.cs"
      
		Echo("Test2");
	}
}

[/code]

http://forums.keenswh.com/threads/generics-the-revenge-request-for-input.7381030/page-2#post-1286958715

**Comment by lord-devious** [comment]
Thank you very much!

**Comment by lord-devious** [comment]
Fixed.
