### ISSUE TITLE
Sharing NestedNode for each of { [], {}, () } can be problematic

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#11]
On analyzing and debugging your code I came across the initialization of the different kinds of patterns that are added at the Injector class. The problem is that the Previous and Next properties are being overridden for each new pattern, because they're using the same NestedNode instance.

For example after the initialization of the WhileLoopPattern the Previous property points to the "While"-CodeNode and the Next property points to an InjectionPointNode.

`Code.While -> <- PARENTHESES -> <- InjectionPoint`

But when it enters the initialization of the ForLoopPattern the same NestedNode (here: NesteNode.PARENTHESES) is being used. Now the Previous and Next property are going to be overridden by the Nodes used by the ForLoopPattern.

```
Code.While ->                   <- InjectionPoint
Code.For   -> <- PARENTHESES -> <- InjectionPoint
```

At this point there is no problem, because both point to an InjectionPoint after the parentheses.
Since MethodPattern is the last pattern that uses NestedNode.PARANTHESES, the Next property of the NesteNode.PARANTHESES points to a "LeftBrace"-CodeNode and so on.

So for our example this looks like this:

```
Code.While                     ->                   <- InjectionPoint
Code.For                       ->                   <- InjectionPoint
PeekNode -> <- Code.Identifier -> <- PARENTHESES -> <- Code.LeftBrace -> <- InjectionPoint
```

When the Injector is using the While- or ForLoopPattern, this will consume the {, because after the parentheses the "LeftBrace"-CodeNode have to be done before the InjectionPoint is reached. But it should reach the InjectionPoint immediately after the parentheses.

So I recommend to use new instances of NesteNode instead of reusing them.

**Comment by albmar** [comment]
Fixing this bug might fix #10, too.

**Comment by lord-devious** [comment]
Thank you very much for your dedication. I can't believe I had _another one_ of these idiotic things in there :tired_face: I fixed a similar one a couple of commits ago. I don't know what my brain was on when I did this but it must have been effective :p

While your efforts are _highly_ appreciated, you don't have to spend so much of your time explaining your findings in _this_ much detail. I am no coding amateur by any means of the word, so a simple explanation is usually enough to point me in the right direction :smile:

**Comment by albmar** [comment]
I automatically tend to explain things in detail, so it's not that I think you wouldn't understand it otherwise. I try to keep that in mind for the next possible issues. :smiley: 

On the other hand it looks more serious if there is more text. :stuck_out_tongue_closed_eyes:

**Comment by lord-devious** [comment]
IMO that's a good attribute. Personally I am _really_ bad at explaining stuff... You do what suits you best, I don't mind. I'm just happy you're willing to help.

**Comment by lord-devious** [comment]
Fixed.
