### ISSUE TITLE
Wrong Syntax Error

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#2]
The following code doesn't have any syntax errors and works fine in the current version (01_127_011 64-bit) of Space Engineers:

[Example code](http://pastebin.com/cFnJ6yHQ)

But it throws an InjectorException with the message "Syntax Error" at [Statement.cs#L104](https://github.com/lord-devious/csharpinjector/blob/48dc85376ce17e424ba5f0ab52774c76ea378142/Source/CSharpInjector/Statement.cs#L104).

**Comment by lord-devious** [comment]
Fantastic, excellent work.

**Comment by lord-devious** [comment]
Fixed.
