### ISSUE TITLE
Unable to understand token

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#3]
An other example that should work, but an InjectorException with message "Tokenization Failure: Unable to understand token" is thrown at [Tokenizer.cs#L58](https://github.com/lord-devious/csharpinjector/blob/48dc85376ce17e424ba5f0ab52774c76ea378142/Source/CSharpInjector/Tokenizer.cs#L58)

[Example Code](http://pastebin.com/xEHKLQzx)

Edit: corrected the error message

**Comment by lord-devious** [comment]
You're on fire! Fantastic!

**Comment by lord-devious** [comment]
Fixed
