### ISSUE TITLE
Integer-type-suffix isn't accepted for hexadecimal numbers

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#6]
All of these combinations should work with hexadecimal numbers as prefixes for long or unsigned types:
U u L l UL Ul uL ul LU Lu lU lu

For the sake of completeness, here some examples:

0xF0UL
0xdeal

**Comment by lord-devious** [comment]
Aagh, of course they should.

**Comment by lord-devious** [comment]
Fixed.
