### ISSUE TITLE
Real-type-suffix isn't accepted

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#7]
Like issue #6, but for floating point values. Suffixes that should be accepted are:
F f D d M m

Examples:
1f, 1.5f, 1e10f, and 123.456F are all of type float
1d, 1.5d, 1e10d, and 123.456D are all of type double
1m, 1.5m, 1e10m, and 123.456M are all of type decimal

**Comment by lord-devious** [comment]
-.- Then my fix for your previous real problem broke this.

Bugger.

**Comment by lord-devious** [comment]
Fixed. Again.
