### ISSUE TITLE
False positive patterns or wrong tokens

### ISSUE THREAD

**Issue by albmar** [lord-devious/csharpinjector#8]
The following table shows form left to right the input text, recognized patterns as it is and the recognized patterns as it should:

Input | Actual | Expected
-------|----------|-------------
`0x` | **IntegerLiteral** `0x` | NaN, not a token?
`0xfeed` | **IntegerLiteral** `0x`, **Identifier** `feed` | **IntegerLiteral** `0xfeed`
_see below_| **StringLiteral** `"break this string` | not a token
```C#
"break this string
to the next line"
```

Input | Actual | Expected
-------|----------|-------------
_see below_| **Identifier** `@`, **StringLiteral** `"break this string` | At least **StringLiteral** `"break this string<newline>to the next line"`. I am not sure about the @.
```
@"break this string
to the next line"
```
Input | Actual | Expected
-------|----------|-------------
`$"this string contains an {identifier}"` | **StringLiteral** `$"this string contains an {identifier}"` | I am not sure here, maybe it is correct, otherwise identifier should be a IdentifierLiteral.
<!--<table>
<tr>
<th>Input</th><th>Actual</th><th>Expected</th>
</tr>
<tr>
<td>`0x`</td><td>**IntegerLiteral** `0x`</td><td>NaN, not a token?</td>
</tr>
<tr>
<td>`0xfeed`</td><td>**IntegerLiteral** `0x`, **Identifier** `feed`</td><td>**IntegerLiteral** `0xfeed`</td>
</tr>
<tr>
<td>
```C#
"break this string
to the next line"
```
</td><td>**StringLiteral** `"break this string`</td><td>not a token</td>
</tr>
<tr>
<td>
```
@"break this string
to the next line"
```</td><td>**Identifier** `@`, **StringLiteral** `"break this string`</td><td>At least **StringLiteral** `"break this string_newline_to the next line"`. I am not sure about the @.</td>
</tr>
<tr>
<td>`$"this string contains an {identifier}"`</td><td>**StringLiteral** `$"this string contains an {identifier}"`</td><td>I am not sure here, maybe it is correct, otherwise identifier should be a IdentifierLiteral.</td>
</tr>
</table>-->

Edit: Formatting at GitHub can be frustrating. :disappointed:

**Comment by lord-devious** [comment]
Does this actually break injection? I have made some shortcuts on purpose.

**Comment by lord-devious** [comment]
I don't believe it. I actually broke hex parsing. :anguished:

**Comment by albmar** [comment]
What do you mean by breaking the injection? There are no errors though, but in my opinion these examples aren't tokenized correctly.

**Comment by lord-devious** [comment]
No, they're not tokenized _correctly_, they're tokenized _quickly _:smile: 

The compiler itself will deal with the details. All I need to do is make sure the instruction counting calls are injected in the right locations. Even the compiler _tokenizes_ 0x as a number, although it is rejected as an _invalid_ number. Try it for yourself :smile: Again it doesn't matter for injection purposes. The string/newline thing is unimportant, again the compiler will stop that but it won't affect injection. 

The hex parsing and @ being parsed as an identifier are both most definitely bugs.

**Comment by lord-devious** [comment]
You may notice that I'm not even registering every individual symbol or keyword as anything else than OtherSymbol and OtherKeyword. That's because I don't need to know about them for the sake of the injection. Since this is going to be compiled afterwards anyway, why should I do double the work? :smile:

**Comment by lord-devious** [comment]
Fixed hex and @ parsing
