### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Dawnkeeper** [lord-devious/csharpinjector#9]
[This](http://pastebin.com/fXuBDxYd) compiles quite fine in the game. Here I get an syntax error.

My guess is that it can't handle the compacted code at the end.

**Comment by lord-devious** [comment]
I doubt it has anything to do with the compacting, it handles the gameboy emulator script :)

But there's still something wrong I can fix, so thank you very much :smile:

**Comment by lord-devious** [comment]
Fixed.
